# Generated by Django 3.1.7 on 2021-06-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mainImage', models.CharField(max_length=1000)),
                ('subImage1', models.CharField(max_length=1000)),
                ('subImage2', models.CharField(max_length=1000)),
                ('subImage3', models.CharField(max_length=1000)),
                ('subImage4', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=100)),
                ('discountedPrice', models.IntegerField(default=0)),
                ('actualPrice', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.category')),
            ],
        ),
    ]
