# Generated by Django 3.1.7 on 2021-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberAvailable',
            field=models.IntegerField(default=0),
        ),
    ]
