# Generated by Django 3.1.7 on 2021-06-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_product_numberavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainImage',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subImage1',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subImage2',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subImage3',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subImage4',
            new_name='image5',
        ),
    ]
